[package]
name = "chip8"
version = "0.1.0"
authors = ["oddg <odegevigney@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.2"
maplit = "1.0"
rand = "0.6"
sdl2 = { version = "0.32.0", features = ["bundled"] }
